// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistrationValidationApp.Data;

#nullable disable

namespace RegistrationValidationApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241029161346_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("RegistrationValidationApp.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Electrified")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Registrations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Electrified = "true",
                            RegistrationNumber = "ABC123"
                        },
                        new
                        {
                            Id = 2,
                            Electrified = "false",
                            RegistrationNumber = "XYZ789"
                        },
                        new
                        {
                            Id = 3,
                            Electrified = "true",
                            RegistrationNumber = "LMN456"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
